name: CI/CD

on:
  push:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.spec'
      - '**.yml'

# Define a reusable variable for common steps
jobs:
  common-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/common-steps.yml

      - name: Build
        run: npm run build

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/common-steps.yml

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test