name: GitHub-Actions

on: 
  push: # runs workflow when push a commit or tag
    paths: # workflow will only run when a push that includes a change in files
      ['**.ts', '**.tsx', '**.spec']

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

  Build:
    needs: Install
      - name: Build
        run: npm run build
  
  Lint:
    needs: Build
      - name: Lint
        run: npm run lint

  Unit_Test:
    needs: Build
      - name: Unit Test
        run: npm run test

