name: GitHub Actions
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
    steps:
      - name: install
        run: npm install
      - name: build 
        run: npm run build
      - name: unit test
        run: npm run test
      - name: lint
        run: npm run lint
      
