name: App actions

on: 
  push:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.spec'
      - '**.yml'

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

  Build:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
        working-directory: '/home/runner/work/to-do-vite'
  
  Lint:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint

  Unit_Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        run: npm run test